In [15]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)

def print_header(title):
    print("\n" + "="*80)
    print(title)
    print("="*80)

In [16]:
print_header("Question 1: (A^T)^T = A")

A = np.random.randn(3, 4)
lhs = (A.T).T
rhs = A

print("A:\n", A)
print("\n(A.T).T:\n", lhs)
print("\nTất cả phần tử bằng nhau? ->", np.allclose(lhs, rhs))



Question 1: (A^T)^T = A
A:
 [[-0.9102  0.5479 -0.7221  1.0354]
 [-0.9516  0.3245  0.2658  0.0925]
 [-1.1146 -0.4813 -1.4471  0.4208]]

(A.T).T:
 [[-0.9102  0.5479 -0.7221  1.0354]
 [-0.9516  0.3245  0.2658  0.0925]
 [-1.1146 -0.4813 -1.4471  0.4208]]

Tất cả phần tử bằng nhau? -> True


In [17]:
print_header("Question 2: A^T + B^T = (A + B)^T")

A = np.random.randn(3, 4)
B = np.random.randn(3, 4)

lhs = A.T + B.T
rhs = (A + B).T

print("A:\n", A)
print("\nB:\n", B)
print("\nA.T + B.T:\n", lhs)
print("\n(A + B).T:\n", rhs)
print("\nTất cả phần tử bằng nhau? ->", np.allclose(lhs, rhs))



Question 2: A^T + B^T = (A + B)^T
A:
 [[-0.2682  0.5193 -0.0781 -0.3545]
 [-0.1915  1.136   1.2594  0.1804]
 [ 0.2686  0.0612 -0.7671  0.3311]]

B:
 [[ 0.0497  0.2701  1.1823  0.0185]
 [ 0.2095 -0.3939  0.573  -1.5295]
 [ 0.0645 -0.4632  0.6009  0.4083]]

A.T + B.T:
 [[-0.2185  0.018   0.3331]
 [ 0.7893  0.7421 -0.402 ]
 [ 1.1042  1.8324 -0.1661]
 [-0.336  -1.349   0.7394]]

(A + B).T:
 [[-0.2185  0.018   0.3331]
 [ 0.7893  0.7421 -0.402 ]
 [ 1.1042  1.8324 -0.1661]
 [-0.336  -1.349   0.7394]]

Tất cả phần tử bằng nhau? -> True


In [18]:
print_header("Question 3: A + A^T có luôn đối xứng không?")

A = np.random.randn(4, 4)

S = A + A.T
S_T = S.T

print("A:\n", A)
print("\nS = A + A.T:\n", S)
print("\nS.T:\n", S_T)
print("\nS có bằng S.T? ->", np.allclose(S, S_T))



Question 3: A + A^T có luôn đối xứng không?
A:
 [[-0.3944 -0.5086  0.2826 -1.0922]
 [-0.4913  0.1083 -1.7347  0.1215]
 [ 0.5529  1.4249  0.0908  0.9884]
 [-0.9822  1.7952 -1.9003  0.1334]]

S = A + A.T:
 [[-0.7888 -0.9998  0.8355 -2.0744]
 [-0.9998  0.2166 -0.3098  1.9166]
 [ 0.8355 -0.3098  0.1816 -0.9119]
 [-2.0744  1.9166 -0.9119  0.2668]]

S.T:
 [[-0.7888 -0.9998  0.8355 -2.0744]
 [-0.9998  0.2166 -0.3098  1.9166]
 [ 0.8355 -0.3098  0.1816 -0.9119]
 [-2.0744  1.9166 -0.9119  0.2668]]

S có bằng S.T? -> True


In [19]:
print_header("Question 4: len(X) với X shape (2, 3, 4)")

X = np.random.randn(2, 3, 4)
print("X shape:", X.shape)
print("len(X):", len(X))


Question 4: len(X) với X shape (2, 3, 4)
X shape: (2, 3, 4)
len(X): 2


In [20]:
print_header("Question 5: len(X) cho tensor arbitrary shape")

shapes = [(5, 7),
          (2, 3, 4),
          (10, 1, 3, 8)]

for shp in shapes:
    X = np.zeros(shp)
    print("Shape:", X.shape, "-> len(X) =", len(X),
          "(bằng X.shape[0] =", X.shape[0], ")")


Question 5: len(X) cho tensor arbitrary shape
Shape: (5, 7) -> len(X) = 5 (bằng X.shape[0] = 5 )
Shape: (2, 3, 4) -> len(X) = 2 (bằng X.shape[0] = 2 )
Shape: (10, 1, 3, 8) -> len(X) = 10 (bằng X.shape[0] = 10 )


In [21]:
print_header("Question 6: A / A.sum(axis=1)")

A = np.random.rand(3, 4)
row_sum = A.sum(axis=1)

print("A:\n", A)
print("\nA.sum(axis=1):", row_sum, " | shape:", row_sum.shape)

B = A / row_sum[:, None]
print("\nB = A / A.sum(axis=1) (dùng broadcast):\n", B)

print("\nSum theo hàng của B (axis=1):", B.sum(axis=1))


Question 6: A / A.sum(axis=1)
A:
 [[0.9303 0.314  0.8717 0.6519]
 [0.2471 0.3959 0.8431 0.9275]
 [0.9194 0.9399 0.1068 0.891 ]]

A.sum(axis=1): [2.7678 2.4136 2.8571]  | shape: (3,)

B = A / A.sum(axis=1) (dùng broadcast):
 [[0.3361 0.1134 0.3149 0.2355]
 [0.1024 0.164  0.3493 0.3843]
 [0.3218 0.329  0.0374 0.3119]]

Sum theo hàng của B (axis=1): [1. 1. 1.]


In [22]:
print_header("Question 7: Manhattan distance")

def manhattan_distance(p, q):
    p = np.array(p)
    q = np.array(q)
    return np.sum(np.abs(p - q))

p = np.array([1, 2])
q = np.array([5, 7])

print("Điểm p:", p, " | điểm q:", q)
print("Khoảng cách Manhattan (|Δavenue| + |Δstreet|) =", manhattan_distance(p, q))
print("Nếu được đi chéo (Euclid) thì khoảng cách =", np.linalg.norm(q - p))
print("\nTrong Manhattan, ta không được đi chéo, nên dùng norm-1.")


Question 7: Manhattan distance
Điểm p: [1 2]  | điểm q: [5 7]
Khoảng cách Manhattan (|Δavenue| + |Δstreet|) = 9
Nếu được đi chéo (Euclid) thì khoảng cách = 6.4031242374328485

Trong Manhattan, ta không được đi chéo, nên dùng norm-1.


In [23]:
print_header("Question 8: Summation shapes với tensor (2, 3, 4)")

X = np.arange(2*3*4).reshape(2, 3, 4)
print("X shape:", X.shape)
print("X:\n", X)

sum0 = X.sum(axis=0)
sum1 = X.sum(axis=1)
sum2 = X.sum(axis=2)

print("\nSum axis=0 -> shape", sum0.shape, ":\n", sum0)
print("\nSum axis=1 -> shape", sum1.shape, ":\n", sum1)
print("\nSum axis=2 -> shape", sum2.shape, ":\n", sum2)


Question 8: Summation shapes với tensor (2, 3, 4)
X shape: (2, 3, 4)
X:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Sum axis=0 -> shape (3, 4) :
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

Sum axis=1 -> shape (2, 4) :
 [[12 15 18 21]
 [48 51 54 57]]

Sum axis=2 -> shape (2, 3) :
 [[ 6 22 38]
 [54 70 86]]


In [24]:
print_header("Question 9: linalg.norm cho tensor nhiều trục")

X = np.random.randn(2, 3, 4)
norm_builtin = np.linalg.norm(X)

sum_squares = np.sum(X**2)
norm_manual = np.sqrt(sum_squares)

print("X shape:", X.shape)
print("\nnp.linalg.norm(X) =", norm_builtin)
print("sqrt(sum(X**2)) =", norm_manual)
print("\nHai giá trị gần như bằng nhau? ->", np.allclose(norm_builtin, norm_manual))


Question 9: linalg.norm cho tensor nhiều trục
X shape: (2, 3, 4)

np.linalg.norm(X) = 4.886156781405914
sqrt(sum(X**2)) = 4.886156781405914

Hai giá trị gần như bằng nhau? -> True


In [25]:
print_header("Question 10: Cost (AB)C vs A(BC) với kích thước lớn")

def cost(m, n, p):
    return m * n * p

a1, a2 = 10, 16
b2, b3 = 5, 5
c3, c4 = 5, 14

cost_AB = cost(2**10, 2**16, 2**5)
cost_ABC_1 = cost_AB + cost(2**10, 2**5, 2**14)

cost_BC = cost(2**16, 2**5, 2**14)
cost_ABC_2 = cost_BC + cost(2**10, 2**16, 2**14)

print("Cost (AB)C ≈ 2^31 + 2^29 ~", cost_ABC_1)
print("Cost A(BC) ≈ 2^35 + 2^40 ~", cost_ABC_2)
print("Tỷ lệ (A(BC)) / ((AB)C) ~", cost_ABC_2 / cost_ABC_1)

print("\n(AB) có shape 2^10 x 2^5 (2^15 phần tử) => ma trận trung gian khá nhỏ.")
print("BC có shape 2^16 x 2^14 (2^30 phần tử) => ma trận trung gian khổng lồ.")


Question 10: Cost (AB)C vs A(BC) với kích thước lớn
Cost (AB)C ≈ 2^31 + 2^29 ~ 2684354560
Cost A(BC) ≈ 2^35 + 2^40 ~ 1133871366144
Tỷ lệ (A(BC)) / ((AB)C) ~ 422.4

(AB) có shape 2^10 x 2^5 (2^15 phần tử) => ma trận trung gian khá nhỏ.
BC có shape 2^16 x 2^14 (2^30 phần tử) => ma trận trung gian khổng lồ.


In [26]:
print_header("Question 11: AB vs AC^T và C = B^T")

m, n, p = 64, 128, 32
A = np.random.randn(m, n)
B = np.random.randn(n, p)
C = np.random.randn(p, n)

AB = A @ B
ACt = A @ C.T

print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)
print("AB shape:", AB.shape)
print("A @ C.T shape:", ACt.shape)
print("\nCost lý thuyết 2 trường hợp giống nhau vì đều là m*n*p phép toán.")

C_view = B.T
ACt_view = A @ C_view.T

print("\nTrường hợp đặc biệt C = B^T:")
print("C_view shape (B.T):", C_view.shape)
print("C_view.T shape:", C_view.T.shape)
print("A @ C_view.T shape:", ACt_view.shape)
print("A @ C_view.T có bằng AB? ->", np.allclose(ACt_view, AB))


Question 11: AB vs AC^T và C = B^T
A shape: (64, 128)
B shape: (128, 32)
C shape: (32, 128)
AB shape: (64, 32)
A @ C.T shape: (64, 32)

Cost lý thuyết 2 trường hợp giống nhau vì đều là m*n*p phép toán.

Trường hợp đặc biệt C = B^T:
C_view shape (B.T): (32, 128)
C_view.T shape: (128, 32)
A @ C_view.T shape: (64, 32)
A @ C_view.T có bằng AB? -> True


In [27]:
print_header("Question 12: Stack [A,B,C] và slice lại B")

A = np.random.randn(100, 200)
B = np.random.randn(100, 200)
C = np.random.randn(100, 200)

T = np.stack([A, B, C], axis=2)

print("A, B, C shape:", A.shape)
print("Tensor T shape:", T.shape)

B_recovered = T[:, :, 1]

print("\nB_recovered shape:", B_recovered.shape)
print("B_recovered có bằng B gốc không? ->", np.allclose(B_recovered, B))


Question 12: Stack [A,B,C] và slice lại B
A, B, C shape: (100, 200)
Tensor T shape: (100, 200, 3)

B_recovered shape: (100, 200)
B_recovered có bằng B gốc không? -> True
