In [15]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)

def print_header(title):
    print("\n" + "="*80)
    print(title)
    print("="*80)

In [16]:
print_header("Question 1: (A^T)^T = A")

A = np.random.randn(3, 4)
lhs = (A.T).T
rhs = A

print("A:\n", A)
print("\n(A.T).T:\n", lhs)
print("\nTất cả phần tử bằng nhau? ->", np.allclose(lhs, rhs))



Question 1: (A^T)^T = A
A:
 [[-0.9102  0.5479 -0.7221  1.0354]
 [-0.9516  0.3245  0.2658  0.0925]
 [-1.1146 -0.4813 -1.4471  0.4208]]

(A.T).T:
 [[-0.9102  0.5479 -0.7221  1.0354]
 [-0.9516  0.3245  0.2658  0.0925]
 [-1.1146 -0.4813 -1.4471  0.4208]]

Tất cả phần tử bằng nhau? -> True


In [17]:
print_header("Question 2: A^T + B^T = (A + B)^T")

A = np.random.randn(3, 4)
B = np.random.randn(3, 4)

lhs = A.T + B.T
rhs = (A + B).T

print("A:\n", A)
print("\nB:\n", B)
print("\nA.T + B.T:\n", lhs)
print("\n(A + B).T:\n", rhs)
print("\nTất cả phần tử bằng nhau? ->", np.allclose(lhs, rhs))



Question 2: A^T + B^T = (A + B)^T
A:
 [[-0.2682  0.5193 -0.0781 -0.3545]
 [-0.1915  1.136   1.2594  0.1804]
 [ 0.2686  0.0612 -0.7671  0.3311]]

B:
 [[ 0.0497  0.2701  1.1823  0.0185]
 [ 0.2095 -0.3939  0.573  -1.5295]
 [ 0.0645 -0.4632  0.6009  0.4083]]

A.T + B.T:
 [[-0.2185  0.018   0.3331]
 [ 0.7893  0.7421 -0.402 ]
 [ 1.1042  1.8324 -0.1661]
 [-0.336  -1.349   0.7394]]

(A + B).T:
 [[-0.2185  0.018   0.3331]
 [ 0.7893  0.7421 -0.402 ]
 [ 1.1042  1.8324 -0.1661]
 [-0.336  -1.349   0.7394]]

Tất cả phần tử bằng nhau? -> True


In [18]:
print_header("Question 3: A + A^T có luôn đối xứng không?")

A = np.random.randn(4, 4)

S = A + A.T
S_T = S.T

print("A:\n", A)
print("\nS = A + A.T:\n", S)
print("\nS.T:\n", S_T)
print("\nS có bằng S.T? ->", np.allclose(S, S_T))



Question 3: A + A^T có luôn đối xứng không?
A:
 [[-0.3944 -0.5086  0.2826 -1.0922]
 [-0.4913  0.1083 -1.7347  0.1215]
 [ 0.5529  1.4249  0.0908  0.9884]
 [-0.9822  1.7952 -1.9003  0.1334]]

S = A + A.T:
 [[-0.7888 -0.9998  0.8355 -2.0744]
 [-0.9998  0.2166 -0.3098  1.9166]
 [ 0.8355 -0.3098  0.1816 -0.9119]
 [-2.0744  1.9166 -0.9119  0.2668]]

S.T:
 [[-0.7888 -0.9998  0.8355 -2.0744]
 [-0.9998  0.2166 -0.3098  1.9166]
 [ 0.8355 -0.3098  0.1816 -0.9119]
 [-2.0744  1.9166 -0.9119  0.2668]]

S có bằng S.T? -> True


In [19]:
print_header("Question 4: len(X) với X shape (2, 3, 4)")

X = np.random.randn(2, 3, 4)
print("X shape:", X.shape)
print("len(X):", len(X))


Question 4: len(X) với X shape (2, 3, 4)
X shape: (2, 3, 4)
len(X): 2


In [20]:
print_header("Question 5: len(X) cho tensor arbitrary shape")

shapes = [(5, 7),
          (2, 3, 4),
          (10, 1, 3, 8)]

for shp in shapes:
    X = np.zeros(shp)
    print("Shape:", X.shape, "-> len(X) =", len(X),
          "(bằng X.shape[0] =", X.shape[0], ")")


Question 5: len(X) cho tensor arbitrary shape
Shape: (5, 7) -> len(X) = 5 (bằng X.shape[0] = 5 )
Shape: (2, 3, 4) -> len(X) = 2 (bằng X.shape[0] = 2 )
Shape: (10, 1, 3, 8) -> len(X) = 10 (bằng X.shape[0] = 10 )


In [21]:
print_header("Question 6: A / A.sum(axis=1)")

A = np.random.rand(3, 4)
row_sum = A.sum(axis=1)

print("A:\n", A)
print("\nA.sum(axis=1):", row_sum, " | shape:", row_sum.shape)

B = A / row_sum[:, None]
print("\nB = A / A.sum(axis=1) (dùng broadcast):\n", B)

print("\nSum theo hàng của B (axis=1):", B.sum(axis=1))


Question 6: A / A.sum(axis=1)
A:
 [[0.9303 0.314  0.8717 0.6519]
 [0.2471 0.3959 0.8431 0.9275]
 [0.9194 0.9399 0.1068 0.891 ]]

A.sum(axis=1): [2.7678 2.4136 2.8571]  | shape: (3,)

B = A / A.sum(axis=1) (dùng broadcast):
 [[0.3361 0.1134 0.3149 0.2355]
 [0.1024 0.164  0.3493 0.3843]
 [0.3218 0.329  0.0374 0.3119]]

Sum theo hàng của B (axis=1): [1. 1. 1.]


In [22]:
print_header("Question 7: Manhattan distance")

def manhattan_distance(p, q):
    p = np.array(p)
    q = np.array(q)
    return np.sum(np.abs(p - q))

p = np.array([1, 2])
q = np.array([5, 7])

print("Điểm p:", p, " | điểm q:", q)
print("Khoảng cách Manhattan (|Δavenue| + |Δstreet|) =", manhattan_distance(p, q))
print("Nếu được đi chéo (Euclid) thì khoảng cách =", np.linalg.norm(q - p))
print("\nTrong Manhattan, ta không được đi chéo, nên dùng norm-1.")


Question 7: Manhattan distance
Điểm p: [1 2]  | điểm q: [5 7]
Khoảng cách Manhattan (|Δavenue| + |Δstreet|) = 9
Nếu được đi chéo (Euclid) thì khoảng cách = 6.4031242374328485

Trong Manhattan, ta không được đi chéo, nên dùng norm-1.


In [23]:
print_header("Question 8: Summation shapes với tensor (2, 3, 4)")

X = np.arange(2*3*4).reshape(2, 3, 4)
print("X shape:", X.shape)
print("X:\n", X)

sum0 = X.sum(axis=0)
sum1 = X.sum(axis=1)
sum2 = X.sum(axis=2)

print("\nSum axis=0 -> shape", sum0.shape, ":\n", sum0)
print("\nSum axis=1 -> shape", sum1.shape, ":\n", sum1)
print("\nSum axis=2 -> shape", sum2.shape, ":\n", sum2)


Question 8: Summation shapes với tensor (2, 3, 4)
X shape: (2, 3, 4)
X:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Sum axis=0 -> shape (3, 4) :
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

Sum axis=1 -> shape (2, 4) :
 [[12 15 18 21]
 [48 51 54 57]]

Sum axis=2 -> shape (2, 3) :
 [[ 6 22 38]
 [54 70 86]]


In [24]:
print_header("Question 9: linalg.norm cho tensor nhiều trục")

X = np.random.randn(2, 3, 4)
norm_builtin = np.linalg.norm(X)

sum_squares = np.sum(X**2)
norm_manual = np.sqrt(sum_squares)

print("X shape:", X.shape)
print("\nnp.linalg.norm(X) =", norm_builtin)
print("sqrt(sum(X**2)) =", norm_manual)
print("\nHai giá trị gần như bằng nhau? ->", np.allclose(norm_builtin, norm_manual))


Question 9: linalg.norm cho tensor nhiều trục
X shape: (2, 3, 4)

np.linalg.norm(X) = 4.886156781405914
sqrt(sum(X**2)) = 4.886156781405914

Hai giá trị gần như bằng nhau? -> True


In [25]:
print_header("Question 10: Cost (AB)C vs A(BC) với kích thước lớn")

def cost(m, n, p):
    return m * n * p

a1, a2 = 10, 16
b2, b3 = 5, 5
c3, c4 = 5, 14

cost_AB = cost(2**10, 2**16, 2**5)
cost_ABC_1 = cost_AB + cost(2**10, 2**5, 2**14)

cost_BC = cost(2**16, 2**5, 2**14)
cost_ABC_2 = cost_BC + cost(2**10, 2**16, 2**14)

print("Cost (AB)C ≈ 2^31 + 2^29 ~", cost_ABC_1)
print("Cost A(BC) ≈ 2^35 + 2^40 ~", cost_ABC_2)
print("Tỷ lệ (A(BC)) / ((AB)C) ~", cost_ABC_2 / cost_ABC_1)

print("\n(AB) có shape 2^10 x 2^5 (2^15 phần tử) => ma trận trung gian khá nhỏ.")
print("BC có shape 2^16 x 2^14 (2^30 phần tử) => ma trận trung gian khổng lồ.")


Question 10: Cost (AB)C vs A(BC) với kích thước lớn
Cost (AB)C ≈ 2^31 + 2^29 ~ 2684354560
Cost A(BC) ≈ 2^35 + 2^40 ~ 1133871366144
Tỷ lệ (A(BC)) / ((AB)C) ~ 422.4

(AB) có shape 2^10 x 2^5 (2^15 phần tử) => ma trận trung gian khá nhỏ.
BC có shape 2^16 x 2^14 (2^30 phần tử) => ma trận trung gian khổng lồ.


In [26]:
print_header("Question 11: AB vs AC^T và C = B^T")

m, n, p = 64, 128, 32
A = np.random.randn(m, n)
B = np.random.randn(n, p)
C = np.random.randn(p, n)

AB = A @ B
ACt = A @ C.T

print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)
print("AB shape:", AB.shape)
print("A @ C.T shape:", ACt.shape)
print("\nCost lý thuyết 2 trường hợp giống nhau vì đều là m*n*p phép toán.")

C_view = B.T
ACt_view = A @ C_view.T

print("\nTrường hợp đặc biệt C = B^T:")
print("C_view shape (B.T):", C_view.shape)
print("C_view.T shape:", C_view.T.shape)
print("A @ C_view.T shape:", ACt_view.shape)
print("A @ C_view.T có bằng AB? ->", np.allclose(ACt_view, AB))


Question 11: AB vs AC^T và C = B^T
A shape: (64, 128)
B shape: (128, 32)
C shape: (32, 128)
AB shape: (64, 32)
A @ C.T shape: (64, 32)

Cost lý thuyết 2 trường hợp giống nhau vì đều là m*n*p phép toán.

Trường hợp đặc biệt C = B^T:
C_view shape (B.T): (32, 128)
C_view.T shape: (128, 32)
A @ C_view.T shape: (64, 32)
A @ C_view.T có bằng AB? -> True


In [27]:
print_header("Question 12: Stack [A,B,C] và slice lại B")

A = np.random.randn(100, 200)
B = np.random.randn(100, 200)
C = np.random.randn(100, 200)

T = np.stack([A, B, C], axis=2)

print("A, B, C shape:", A.shape)
print("Tensor T shape:", T.shape)

B_recovered = T[:, :, 1]

print("\nB_recovered shape:", B_recovered.shape)
print("B_recovered có bằng B gốc không? ->", np.allclose(B_recovered, B))


Question 12: Stack [A,B,C] và slice lại B
A, B, C shape: (100, 200)
Tensor T shape: (100, 200, 3)

B_recovered shape: (100, 200)
B_recovered có bằng B gốc không? -> True


In [31]:
print_header("Question 20: Eigenvalues & eigenvectors of A = [[2,1],[1,2]]")

A = np.array([[2, 1],
              [1, 2]], dtype=float)

# Symmetric matrix => use eigh (real eigenvalues, orthonormal eigenvectors)
eigenvalues, eigenvectors = np.linalg.eigh(A)  # ascending order

print("A =\n", A)
print("\nEigenvalues (ascending) =", eigenvalues)
print("Eigenvectors (columns correspond to eigenvalues) =\n", eigenvectors)

print("\nVerification: residuals A v - lambda v")
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    residual = A @ v - lam * v
    print(f"i={i}, lambda={lam:.4f}, residual={residual}")

# Short explanation (printed)
print("\nExplanation:")
print("A is symmetric, so np.linalg.eigh returns real eigenvalues and orthonormal eigenvectors.")
print("Each column v satisfies A v = lambda v (residuals above are ~ 0).")
print("The eigenvalues should be close to [1, 3] (ascending).")



Question 20: Eigenvalues & eigenvectors of A = [[2,1],[1,2]]
A =
 [[2. 1.]
 [1. 2.]]

Eigenvalues (ascending) = [1. 3.]
Eigenvectors (columns correspond to eigenvalues) =
 [[-0.7071  0.7071]
 [ 0.7071  0.7071]]

Verification: residuals A v - lambda v
i=0, lambda=1.0000, residual=[0. 0.]
i=1, lambda=3.0000, residual=[0. 0.]

Explanation:
A is symmetric, so np.linalg.eigh returns real eigenvalues and orthonormal eigenvectors.
Each column v satisfies A v = lambda v (residuals above are ~ 0).
The eigenvalues should be close to [1, 3] (ascending).


In [34]:
print_header("Question 13: Angle between v1 and v2")

v1 = np.array([1, 0, -1, 2], dtype=float)
v2 = np.array([3, 1, 0, 1], dtype=float)

dot = float(v1 @ v2)
n1 = float(np.linalg.norm(v1))
n2 = float(np.linalg.norm(v2))

cos_theta = dot / (n1 * n2)
cos_theta_clipped = float(np.clip(cos_theta, -1.0, 1.0))

theta_rad = float(np.arccos(cos_theta_clipped))
theta_deg = float(np.degrees(theta_rad))

print("v1 =", v1)
print("v2 =", v2)
print("\nv1 · v2 =", dot)
print("||v1|| =", n1)
print("||v2|| =", n2)
print("cos(theta) =", cos_theta)
print("theta (radians) =", theta_rad)
print("theta (degrees) =", theta_deg)

print("\nExplanation:")
print("Angle is computed by cos(theta) = (v1·v2) / (||v1|| ||v2||), then theta = arccos(cos(theta)).")
print("Clipping is used only to avoid tiny numerical errors pushing cos(theta) slightly outside [-1, 1].")



Question 13: Angle between v1 and v2
v1 = [ 1.  0. -1.  2.]
v2 = [3. 1. 0. 1.]

v1 · v2 = 5.0
||v1|| = 2.449489742783178
||v2|| = 3.3166247903554
cos(theta) = 0.6154574548966638
theta (radians) = 0.9078300905002588
theta (degrees) = 52.0148327006444

Explanation:
Angle is computed by cos(theta) = (v1·v2) / (||v1|| ||v2||), then theta = arccos(cos(theta)).
Clipping is used only to avoid tiny numerical errors pushing cos(theta) slightly outside [-1, 1].


In [35]:
print_header("Question 14: True/False: [[1,2],[0,1]] and [[1,-2],[0,1]] are inverses")

A = np.array([[1,  2],
              [0,  1]], dtype=float)

B = np.array([[1, -2],
              [0,  1]], dtype=float)

I = np.eye(2)

AB = A @ B
BA = B @ A

print("A =\n", A)
print("\nB =\n", B)
print("\nA @ B =\n", AB)
print("\nB @ A =\n", BA)

print("\nIs A @ B equal to I? =", np.allclose(AB, I))
print("Is B @ A equal to I? =", np.allclose(BA, I))

print("\nExplanation:")
print("Two matrices are inverses if both A B = I and B A = I.")
print("The products printed above show whether the inverse relationship holds in both directions.")



Question 14: True/False: [[1,2],[0,1]] and [[1,-2],[0,1]] are inverses
A =
 [[1. 2.]
 [0. 1.]]

B =
 [[ 1. -2.]
 [ 0.  1.]]

A @ B =
 [[1. 0.]
 [0. 1.]]

B @ A =
 [[1. 0.]
 [0. 1.]]

Is A @ B equal to I? = True
Is B @ A equal to I? = True

Explanation:
Two matrices are inverses if both A B = I and B A = I.
The products printed above show whether the inverse relationship holds in both directions.


In [36]:
print_header("Question 15: Area scaling after transforming by A = [[2,3],[1,2]]")

area_original = 100.0  # m^2
A = np.array([[2, 3],
              [1, 2]], dtype=float)

detA = float(np.linalg.det(A))
scale = abs(detA)
area_new = area_original * scale

print("A =\n", A)
print("\ndet(A) =", detA)
print("Area scale factor = |det(A)| =", scale)
print("Original area =", area_original)
print("New area =", area_new)

print("\nExplanation:")
print("A linear transform in 2D scales area by |det(A)|.")
print("So the transformed area equals original_area * |det(A)|.")



Question 15: Area scaling after transforming by A = [[2,3],[1,2]]
A =
 [[2. 3.]
 [1. 2.]]

det(A) = 1.0
Area scale factor = |det(A)| = 1.0
Original area = 100.0
New area = 100.0

Explanation:
A linear transform in 2D scales area by |det(A)|.
So the transformed area equals original_area * |det(A)|.


In [37]:
print_header("Question 16: Which sets of vectors are linearly independent?")

def is_linearly_independent(vectors, tol=1e-12):
    M = np.column_stack(vectors).astype(float)
    r = np.linalg.matrix_rank(M, tol=tol)
    return r == M.shape[1], r, M

sets = [
    (
        "Set 1",
        [np.array([1, 0, -1], dtype=float),
         np.array([2, 1, -1], dtype=float),
         np.array([3, 1,  1], dtype=float)]
    ),
    (
        "Set 2",
        [np.array([3, 1, 1], dtype=float),
         np.array([1, 1, 1], dtype=float),
         np.array([0, 0, 0], dtype=float)]
    ),
    (
        "Set 3",
        [np.array([1, 1,  0], dtype=float),
         np.array([0, 1, -1], dtype=float),
         np.array([1, 0,  1], dtype=float)]
    ),
]

for name, vecs in sets:
    independent, rank, M = is_linearly_independent(vecs)
    print(name)
    print("Vectors =", vecs)
    print("Matrix with vectors as columns =\n", M)
    print("rank =", rank, "out of", M.shape[1])
    print("Linearly independent? =", independent)
    print()

print("Explanation:")
print("A set of k vectors is linearly independent iff the matrix formed by stacking them as columns has rank k.")
print("If any set contains the zero vector, it is automatically linearly dependent.")



Question 16: Which sets of vectors are linearly independent?
Set 1
Vectors = [array([ 1.,  0., -1.]), array([ 2.,  1., -1.]), array([3., 1., 1.])]
Matrix with vectors as columns =
 [[ 1.  2.  3.]
 [ 0.  1.  1.]
 [-1. -1.  1.]]
rank = 3 out of 3
Linearly independent? = True

Set 2
Vectors = [array([3., 1., 1.]), array([1., 1., 1.]), array([0., 0., 0.])]
Matrix with vectors as columns =
 [[3. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]
rank = 2 out of 3
Linearly independent? = False

Set 3
Vectors = [array([1., 1., 0.]), array([ 0.,  1., -1.]), array([1., 0., 1.])]
Matrix with vectors as columns =
 [[ 1.  0.  1.]
 [ 1.  1.  0.]
 [ 0. -1.  1.]]
rank = 2 out of 3
Linearly independent? = False

Explanation:
A set of k vectors is linearly independent iff the matrix formed by stacking them as columns has rank k.
If any set contains the zero vector, it is automatically linearly dependent.


In [38]:
print_header("Question 17: True/False: det(A) is always 0 if A = [c;d][a b]")

def build_outer(a, b, c, d):
    u = np.array([[c], [d]], dtype=float)
    vT = np.array([[a, b]], dtype=float)
    return u @ vT

# Demonstrate with several random choices
rng = np.random.default_rng(42)

for t in range(5):
    a, b, c, d = rng.integers(-5, 6, size=4)
    A = build_outer(a, b, c, d)
    detA = float(np.linalg.det(A))
    rankA = int(np.linalg.matrix_rank(A))
    print(f"trial {t+1}: a={a}, b={b}, c={c}, d={d}")
    print("A =\n", A)
    print("det(A) =", detA)
    print("rank(A) =", rankA)
    print()

print("Explanation:")
print("A = u v^T is an outer product, so rank(A) <= 1.")
print("Any 2x2 matrix with rank < 2 is singular, hence det(A) = 0 (up to numerical precision).")



Question 17: True/False: det(A) is always 0 if A = [c;d][a b]
trial 1: a=-5, b=3, c=2, d=-1
A =
 [[-10.   6.]
 [  5.  -3.]]
det(A) = 0.0
rank(A) = 1

trial 2: a=-1, b=4, c=-5, d=2
A =
 [[  5. -20.]
 [ -2.   8.]]
det(A) = -2.2204460492503135e-15
rank(A) = 1

trial 3: a=-3, b=-4, c=0, d=5
A =
 [[  0.   0.]
 [-15. -20.]]
det(A) = 0.0
rank(A) = 1

trial 4: a=3, b=3, c=2, d=3
A =
 [[6. 6.]
 [9. 9.]]
det(A) = -2.997602166487925e-15
rank(A) = 1

trial 5: a=0, b=-4, c=4, d=-1
A =
 [[  0. -16.]
 [  0.   4.]]
det(A) = 0.0
rank(A) = 1

Explanation:
A = u v^T is an outer product, so rank(A) <= 1.
Any 2x2 matrix with rank < 2 is singular, hence det(A) = 0 (up to numerical precision).


In [39]:
print_header("Question 18: Condition on A so that Ae1 and Ae2 are orthogonal")

e1 = np.array([1, 0], dtype=float)
e2 = np.array([0, 1], dtype=float)

# Example matrix (you can replace this with your own A)
A = np.array([[2.0,  1.0],
              [3.0, -6.0]], dtype=float)

Ae1 = A @ e1  # first column of A
Ae2 = A @ e2  # second column of A
dot = float(Ae1 @ Ae2)

print("A =\n", A)
print("\ne1 =", e1, "e2 =", e2)
print("Ae1 =", Ae1)
print("Ae2 =", Ae2)
print("Ae1 · Ae2 =", dot)
print("Orthogonal? =", np.isclose(dot, 0.0))

print("\nExplanation:")
print("Ae1 is the first column of A, and Ae2 is the second column of A.")
print("Condition for orthogonality is (Ae1)^T (Ae2) = 0, i.e., the two columns of A must have dot product 0.")
print("If A = [[p, q],[r, s]], the condition is p q + r s = 0.")



Question 18: Condition on A so that Ae1 and Ae2 are orthogonal
A =
 [[ 2.  1.]
 [ 3. -6.]]

e1 = [1. 0.] e2 = [0. 1.]
Ae1 = [2. 3.]
Ae2 = [ 1. -6.]
Ae1 · Ae2 = -16.0
Orthogonal? = False

Explanation:
Ae1 is the first column of A, and Ae2 is the second column of A.
Condition for orthogonality is (Ae1)^T (Ae2) = 0, i.e., the two columns of A must have dot product 0.
If A = [[p, q],[r, s]], the condition is p q + r s = 0.


In [40]:
print_header("Question 19: Einstein notation for tr(A^4) and numerical verification")

# Example matrix (can be any square matrix)
A = np.array([[1.2, 0.3, -0.1],
              [0.0, 2.0,  0.5],
              [0.4, 0.0,  1.5]], dtype=float)

A4 = np.linalg.matrix_power(A, 4)
trace_direct = float(np.trace(A4))

# Einstein-style contraction: tr(A^4) = A_{ij} A_{jk} A_{kl} A_{li}
trace_einsum = float(np.einsum("ij,jk,kl,li->", A, A, A, A))

print("A =\n", A)
print("\ntr(A^4) via trace(matrix_power) =", trace_direct)
print("tr(A^4) via Einstein contraction =", trace_einsum)
print("Absolute difference =", abs(trace_direct - trace_einsum))

print("\nExplanation:")
print("Einstein notation for tr(A^4) is A_{ij} A_{jk} A_{k\\ell} A_{\\ell i} (sum over repeated indices).")
print("np.einsum implements exactly this repeated-index summation, matching np.trace(A^4).")



Question 19: Einstein notation for tr(A^4) and numerical verification
A =
 [[ 1.2  0.3 -0.1]
 [ 0.   2.   0.5]
 [ 0.4  0.   1.5]]

tr(A^4) via trace(matrix_power) = 23.388900000000003
tr(A^4) via Einstein contraction = 23.388900000000003
Absolute difference = 0.0

Explanation:
Einstein notation for tr(A^4) is A_{ij} A_{jk} A_{k\ell} A_{\ell i} (sum over repeated indices).
np.einsum implements exactly this repeated-index summation, matching np.trace(A^4).


In [32]:
print_header("Question 21: Eigenvalues & eigenvectors of A = [[2,1],[0,2]]")

A = np.array([[2, 1],
              [0, 2]], dtype=float)

# General matrix => use eig
eigenvalues, eigenvectors = np.linalg.eig(A)

print("A =\n", A)
print("\nEigenvalues =", eigenvalues)
print("Eigenvectors (columns correspond to eigenvalues) =\n", eigenvectors)

print("\nVerification: residuals A v - lambda v")
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    residual = A @ v - lam * v
    print(f"i={i}, lambda={lam:.4f}, residual={residual}")

# Show nullspace direction of (A - 2I) via SVD (numerical)
B = A - 2*np.eye(2)
U, S, VT = np.linalg.svd(B)

print("\nA - 2I =\n", B)
print("Singular values of (A - 2I) =", S)

null_vec = VT.T[:, -1]  # direction with smallest singular value
print("One nullspace direction (eigenvector direction for lambda=2) =", null_vec)
print("Check (A - 2I) @ null_vec =", B @ null_vec)

# Short explanation (printed)
print("\nExplanation:")
print("A is upper-triangular, so its eigenvalues are the diagonal entries: [2, 2].")
print("There is only one independent eigenvector direction (the nullspace of A-2I is 1D),")
print("which is why this matrix is not diagonalizable (it corresponds to a 2x2 Jordan block).")




Question 21: Eigenvalues & eigenvectors of A = [[2,1],[0,2]]
A =
 [[2. 1.]
 [0. 2.]]

Eigenvalues = [2. 2.]
Eigenvectors (columns correspond to eigenvalues) =
 [[ 1. -1.]
 [ 0.  0.]]

Verification: residuals A v - lambda v
i=0, lambda=2.0000, residual=[0. 0.]
i=1, lambda=2.0000, residual=[0. 0.]

A - 2I =
 [[0. 1.]
 [0. 0.]]
Singular values of (A - 2I) = [1. 0.]
One nullspace direction (eigenvector direction for lambda=2) = [-1.  0.]
Check (A - 2I) @ null_vec = [0. 0.]

Explanation:
A is upper-triangular, so its eigenvalues are the diagonal entries: [2, 2].
There is only one independent eigenvector direction (the nullspace of A-2I is 1D),
which is why this matrix is not diagonalizable (it corresponds to a 2x2 Jordan block).


In [33]:
print_header("Question 22: Check if smallest eigenvalue < 0.5 (and Gershgorin bound)")

A = np.array([[3.0, 0.1, 0.3, 1.0],
              [0.1, 1.0, 0.1, 0.2],
              [0.3, 0.1, 5.0, 0.0],
              [1.0, 0.2, 0.0, 1.8]], dtype=float)

print("A =\n", A)

# Symmetric => eigvalsh gives sorted real eigenvalues
eigenvalues = np.linalg.eigvalsh(A)
lam_min = eigenvalues[0]

print("\nEigenvalues (ascending) =", eigenvalues)
print("Smallest eigenvalue =", lam_min)
print("Is smallest eigenvalue < 0.5? =", lam_min < 0.5)

# Gershgorin lower bound
diag = np.diag(A)
radii = np.sum(np.abs(A), axis=1) - np.abs(diag)
lower_bounds = diag - radii
upper_bounds = diag + radii

print("\nGershgorin intervals by row:")
for i in range(A.shape[0]):
    print(f"row {i+1}: center={diag[i]:.4f}, radius={radii[i]:.4f}, interval=[{lower_bounds[i]:.4f}, {upper_bounds[i]:.4f}]")

global_lb = float(np.min(lower_bounds))
print("\nGershgorin global lower bound =", global_lb)
print("So Gershgorin implies lambda_min >= global_lb, hence lambda_min < 0.5 is possible? =", global_lb < 0.5)

# Short explanation (printed)
print("\nExplanation:")
print("np.linalg.eigvalsh computes the exact eigenvalues numerically for a symmetric matrix.")
print("Gershgorin gives a quick bound: every eigenvalue lies in at least one interval shown above.")
print("If the global lower bound is > 0.5, then lambda_min cannot be < 0.5.")




Question 22: Check if smallest eigenvalue < 0.5 (and Gershgorin bound)
A =
 [[3.  0.1 0.3 1. ]
 [0.1 1.  0.1 0.2]
 [0.3 0.1 5.  0. ]
 [1.  0.2 0.  1.8]]

Eigenvalues (ascending) = [0.9305 1.2826 3.5314 5.0555]
Smallest eigenvalue = 0.9305025203782891
Is smallest eigenvalue < 0.5? = False

Gershgorin intervals by row:
row 1: center=3.0000, radius=1.4000, interval=[1.6000, 4.4000]
row 2: center=1.0000, radius=0.4000, interval=[0.6000, 1.4000]
row 3: center=5.0000, radius=0.4000, interval=[4.6000, 5.4000]
row 4: center=1.8000, radius=1.2000, interval=[0.6000, 3.0000]

Gershgorin global lower bound = 0.5999999999999999
So Gershgorin implies lambda_min >= global_lb, hence lambda_min < 0.5 is possible? = False

Explanation:
np.linalg.eigvalsh computes the exact eigenvalues numerically for a symmetric matrix.
Gershgorin gives a quick bound: every eigenvalue lies in at least one interval shown above.
If the global lower bound is > 0.5, then lambda_min cannot be < 0.5.
