In [10]:
# Cell 1: Import và thiết lập ban đầu

import torch

torch.set_printoptions(precision=3, sci_mode=False)


In [11]:
# Cell 2: Khởi tạo tập nghiệm chung dùng cho cả 3 cụm

# Scalars (tensor 0D)
alpha1 = torch.tensor(-2.0)
alpha2 = torch.tensor(-0.5)
alpha3 = torch.tensor(0.0)
alpha4 = torch.tensor(0.5)
alpha5 = torch.tensor(2.0)

scalars = [alpha1, alpha2, alpha3, alpha4, alpha5]

# Vectors (tensor 1D, R^3)
v1 = torch.tensor([1., 0., 0.])
v2 = torch.tensor([1., 2., 3.])
v3 = torch.tensor([-1., 1., 0.])
v4 = torch.tensor([0.5, 0.5, 0.5])
v5 = torch.tensor([10., 0., 0.])
vectors = [v1, v2, v3, v4, v5]

# Matrices
# A1: 2 x 3 (samples x features)
A1 = torch.tensor([
    [1.,  2.,  0.],
    [3.,  1.,  1.]
])

# A2: 3 x 2 (features x output_dim)
A2 = torch.tensor([
    [1.,  0.],
    [0.,  1.],
    [2., -1.]
])

# A3: 2 x 2 identity
A3 = torch.eye(2)

# A4: 2 x 2 diagonal
A4 = torch.diag(torch.tensor([2., 0.5]))

# A5: 2 x 2 "random" but dễ nhìn
A5 = torch.tensor([
    [4., -1.],
    [2.,  3.]
])

matrices = [A1, A2, A3, A4, A5]

# Tensor 3D: 5 samples, 3 time steps, 4 features
T_seq = torch.arange(5 * 3 * 4, dtype=torch.float32).reshape(5, 3, 4)

# Tensor 4D: 2 images, 1 channel, height=2, width=3
T_img = torch.arange(2 * 1 * 2 * 3, dtype=torch.float32).reshape(2, 1, 2, 3)

print("Tập nghiệm đã khởi tạo.")


Tập nghiệm đã khởi tạo.


In [12]:
# Cell 3A: Cụm A – kiểm tra scalars, vectors, matrices, higher-order tensors

print("=== Scalars (0D tensors) ===")
for i, a in enumerate(scalars, start=1):
    print(f"alpha{i}: value = {a.item():>5},  shape = {a.shape},  dim = {a.dim()}")

print("\n=== Vectors (1D tensors) ===")
for i, v in enumerate(vectors, start=1):
    print(f"v{i} = {v},  shape = {v.shape},  dim = {v.dim()}")

print("\nIndexing demo for v2:")
print("v2      =", v2)
print("v2[0]   =", v2[0].item())
print("v2[1:]  =", v2[1:])

print("\n=== Matrices (2D tensors) ===")
for i, M in enumerate(matrices, start=1):
    print(f"A{i} =\n{M}")
    print("  shape =", M.shape, ", dim =", M.dim(), ", numel =", M.numel())
    print()

print("Diễn giải hàng/cột trên A1:")
print("A1 =\n", A1)
print("Hàng thứ 0 (mẫu 1)       :", A1[0])
print("Hàng thứ 1 (mẫu 2)       :", A1[1])
print("Cột thứ 0 (feature 1)    :", A1[:, 0])
print("Cột thứ 2 (feature 3)    :", A1[:, 2])

print("\n=== Higher-order tensors ===")
print("T_seq shape =", T_seq.shape, ", dim =", T_seq.dim())
print("T_seq[0]      (sample 0)         shape:", T_seq[0].shape)
print("T_seq[0, 1]   (sample 0, t=1)    shape:", T_seq[0, 1].shape)
print("T_seq[:, :, 0] (all, feature 0)  shape:", T_seq[:, :, 0].shape)

print("\nT_img shape =", T_img.shape, ", dim =", T_img.dim())
print("T_img[0]      (image 0)          shape:", T_img[0].shape)
print("T_img[0, 0]   (image 0, channel) shape:", T_img[0, 0].shape)


=== Scalars (0D tensors) ===
alpha1: value =  -2.0,  shape = torch.Size([]),  dim = 0
alpha2: value =  -0.5,  shape = torch.Size([]),  dim = 0
alpha3: value =   0.0,  shape = torch.Size([]),  dim = 0
alpha4: value =   0.5,  shape = torch.Size([]),  dim = 0
alpha5: value =   2.0,  shape = torch.Size([]),  dim = 0

=== Vectors (1D tensors) ===
v1 = tensor([1., 0., 0.]),  shape = torch.Size([3]),  dim = 1
v2 = tensor([1., 2., 3.]),  shape = torch.Size([3]),  dim = 1
v3 = tensor([-1.,  1.,  0.]),  shape = torch.Size([3]),  dim = 1
v4 = tensor([0.500, 0.500, 0.500]),  shape = torch.Size([3]),  dim = 1
v5 = tensor([10.,  0.,  0.]),  shape = torch.Size([3]),  dim = 1

Indexing demo for v2:
v2      = tensor([1., 2., 3.])
v2[0]   = 1.0
v2[1:]  = tensor([2., 3.])

=== Matrices (2D tensors) ===
A1 =
tensor([[1., 2., 0.],
        [3., 1., 1.]])
  shape = torch.Size([2, 3]) , dim = 2 , numel = 6

A2 =
tensor([[ 1.,  0.],
        [ 0.,  1.],
        [ 2., -1.]])
  shape = torch.Size([3, 2]) , dim = 

In [13]:
# Cell 4B-1: Tính chất cộng, nhân với scalar, Hadamard vs cộng

print("=== Cụm B.1 – Properties of addition and scalar multiplication ===")

x, y, z = v2, v3, v4
print("x =", x)
print("y =", y)
print("z =", z)

print("\nGiao hoán cộng trên vector:")
print("x + y =", x + y)
print("y + x =", y + x)
print("Equal? =", torch.allclose(x + y, y + x))

print("\nKết hợp cộng trên vector:")
print("(x + y) + z =", (x + y) + z)
print("x + (y + z) =", x + (y + z))
print("Equal? =", torch.allclose((x + y) + z, x + (y + z)))

alpha = alpha5  # 2.0
print("\nPhân phối nhân vô hướng trên vector:")
print("alpha =", alpha.item())
print("alpha * (x + y)     =", alpha * (x + y))
print("alpha * x + alpha*y =", alpha * x + alpha * y)
print("Equal? =", torch.allclose(alpha * (x + y),
                                alpha * x + alpha * y))

print("\nLặp lại kiểm tra trên ma trận A3, A4")
beta = alpha2  # -0.5
print("beta =", beta.item())
print("A3 =\n", A1)
print("A4 =\n", A5)
print("A3 + A4 =\n", A3 + A4)
print("A4 + A3 =\n", A4 + A3)
print("Equal? =", torch.allclose(A3 + A4, A4 + A3))

left_mat  = beta * (A3 + A4)
right_mat = beta * A3 + beta * A4
print("beta * (A3 + A4) =\n", left_mat)
print("beta * A3 + beta * A4 =\n", right_mat)
print("Equal? =", torch.allclose(left_mat, right_mat))

print("\nSo sánh Hadamard product và cộng phần tử:")
print("x * y (Hadamard) =", x * y)
print("x + y            =", x + y)


=== Cụm B.1 – Properties of addition and scalar multiplication ===
x = tensor([1., 2., 3.])
y = tensor([-1.,  1.,  0.])
z = tensor([0.500, 0.500, 0.500])

Giao hoán cộng trên vector:
x + y = tensor([0., 3., 3.])
y + x = tensor([0., 3., 3.])
Equal? = True

Kết hợp cộng trên vector:
(x + y) + z = tensor([0.500, 3.500, 3.500])
x + (y + z) = tensor([0.500, 3.500, 3.500])
Equal? = True

Phân phối nhân vô hướng trên vector:
alpha = 2.0
alpha * (x + y)     = tensor([0., 6., 6.])
alpha * x + alpha*y = tensor([0., 6., 6.])
Equal? = True

Lặp lại kiểm tra trên ma trận A3, A4
beta = -0.5
A3 =
 tensor([[1., 2., 0.],
        [3., 1., 1.]])
A4 =
 tensor([[ 4., -1.],
        [ 2.,  3.]])
A3 + A4 =
 tensor([[3.000, 0.000],
        [0.000, 1.500]])
A4 + A3 =
 tensor([[3.000, 0.000],
        [0.000, 1.500]])
Equal? = True
beta * (A3 + A4) =
 tensor([[-1.500, -0.000],
        [-0.000, -0.750]])
beta * A3 + beta * A4 =
 tensor([[-1.500, -0.000],
        [-0.000, -0.750]])
Equal? = True

So sánh Hadamard p

In [14]:
# Cell 4B-2: Reduction (sum, mean, max) – vector, matrix, tensor 3D

print("=== Cụm B.2 – Reduction: sum, mean, max ===")

print("v2 =", v2)
print("v2.sum()  =", v2.sum())
print("v2.mean() =", v2.mean())
print("v2.max()  =", v2.max())

print("\nReduction trên A1:")
print("A1 =\n", A1)
print("Sum over rows   (dim=0):", A1.sum(dim=0))
print("Sum over columns(dim=1):", A1.sum(dim=1))

sum_no_keep = A1.sum(dim=1)
sum_keep    = A1.sum(dim=1, keepdim=True)
print("\nSo sánh keepdim:")
print("Without keepdim:", sum_no_keep, "shape =", sum_no_keep.shape)
print("With    keepdim:", sum_keep,    "shape =", sum_keep.shape)

print("\nReduction trên T_seq:")
print("T_seq shape:", T_seq.shape)
print("Sum over batch   (dim=0), shape", T_seq.sum(dim=0).shape)
print("Sum over time    (dim=1), shape", T_seq.sum(dim=1).shape)
print("Sum over feature (dim=2), shape", T_seq.sum(dim=2).shape)

# Thí nghiệm chuẩn hóa theo hàng A / A.sum(axis=1)
print("\nChuẩn hóa theo hàng (row-normalization) trên A1:")
row_sums = A1.sum(dim=1, keepdim=True)
A1_row_normalized = A1 / row_sums
print("A1 =\n", A1)
print("Row sums =\n", row_sums)
print("A1 normalized by row sums =\n", A1_row_normalized)
print("Row sums of normalized A1 =", A1_row_normalized.sum(dim=1))


=== Cụm B.2 – Reduction: sum, mean, max ===
v2 = tensor([1., 2., 3.])
v2.sum()  = tensor(6.)
v2.mean() = tensor(2.)
v2.max()  = tensor(3.)

Reduction trên A1:
A1 =
 tensor([[1., 2., 0.],
        [3., 1., 1.]])
Sum over rows   (dim=0): tensor([4., 3., 1.])
Sum over columns(dim=1): tensor([3., 5.])

So sánh keepdim:
Without keepdim: tensor([3., 5.]) shape = torch.Size([2])
With    keepdim: tensor([[3.],
        [5.]]) shape = torch.Size([2, 1])

Reduction trên T_seq:
T_seq shape: torch.Size([5, 3, 4])
Sum over batch   (dim=0), shape torch.Size([3, 4])
Sum over time    (dim=1), shape torch.Size([5, 4])
Sum over feature (dim=2), shape torch.Size([5, 3])

Chuẩn hóa theo hàng (row-normalization) trên A1:
A1 =
 tensor([[1., 2., 0.],
        [3., 1., 1.]])
Row sums =
 tensor([[3.],
        [5.]])
A1 normalized by row sums =
 tensor([[0.333, 0.667, 0.000],
        [0.600, 0.200, 0.200]])
Row sums of normalized A1 = tensor([1., 1.])


In [15]:
# Cell 4B-3: Non-reduction sum và broadcasting

print("=== Cụm B.3 – Non-reduction sum và broadcasting ===")

print("Vector cộng vector:")
print("v2 =", v2)
print("v3 =", v3)
print("v2 + v3 =", v2 + v3)

print("\nMatrix cộng matrix (A3, A4):")
print("A3 =\n", A3)
print("A4 =\n", A4)
print("A3 + A4 =\n", A3 + A4)

print("\nBroadcasting scalar với matrix A1:")
print("alpha4 =", alpha4.item())
print("A1 + alpha4 =\n", A1 + alpha4)

print("\nBroadcasting vector theo cột:")
X = torch.tensor([
    [1.,  2.,  0.],
    [3.,  1.,  1.],
    [0.,  0.,  1.],
    [2.,  3.,  4.],
    [4.,  1., -1.]
])
b_feat = torch.tensor([0.1, -0.2, 0.3])

print("X shape      =", X.shape)
print("b_feat shape =", b_feat.shape)
print("X + b_feat =\n", X + b_feat)

print("\nBroadcasting trên tensor 3D T_seq (theo feature):")
feat_bias = torch.tensor([0.5, 0., -0.5, 1.0])
print("T_seq shape     =", T_seq.shape)
print("feat_bias shape =", feat_bias.shape)
print("T_seq + feat_bias shape =", (T_seq + feat_bias).shape)


=== Cụm B.3 – Non-reduction sum và broadcasting ===
Vector cộng vector:
v2 = tensor([1., 2., 3.])
v3 = tensor([-1.,  1.,  0.])
v2 + v3 = tensor([0., 3., 3.])

Matrix cộng matrix (A3, A4):
A3 =
 tensor([[1., 0.],
        [0., 1.]])
A4 =
 tensor([[2.000, 0.000],
        [0.000, 0.500]])
A3 + A4 =
 tensor([[3.000, 0.000],
        [0.000, 1.500]])

Broadcasting scalar với matrix A1:
alpha4 = 0.5
A1 + alpha4 =
 tensor([[1.500, 2.500, 0.500],
        [3.500, 1.500, 1.500]])

Broadcasting vector theo cột:
X shape      = torch.Size([5, 3])
b_feat shape = torch.Size([3])
X + b_feat =
 tensor([[ 1.100,  1.800,  0.300],
        [ 3.100,  0.800,  1.300],
        [ 0.100, -0.200,  1.300],
        [ 2.100,  2.800,  4.300],
        [ 4.100,  0.800, -0.700]])

Broadcasting trên tensor 3D T_seq (theo feature):
T_seq shape     = torch.Size([5, 3, 4])
feat_bias shape = torch.Size([4])
T_seq + feat_bias shape = torch.Size([5, 3, 4])


In [16]:
# Cell 4B-4: Dot product

print("=== Cụm B.4 – Dot product ===")

def show_dot(a, b, name_a, name_b):
    dot1 = torch.dot(a, b)
    dot2 = (a * b).sum()
    print(f"{name_a} · {name_b} via torch.dot = {dot1}")
    print(f"{name_a} · {name_b} via sum(a*b)  = {dot2}")
    print("Equal? =", torch.allclose(dot1, dot2))
    print()

show_dot(v1, v5, "v1", "v5")
show_dot(v2, v4, "v2", "v4")
show_dot(v2, v3, "v2", "v3")

print("Dot product như weighted sum:")
w = v4
x_vec = v2
print("w =", w)
print("x_vec =", x_vec)
print("w · x_vec =", torch.dot(w, x_vec))


=== Cụm B.4 – Dot product ===
v1 · v5 via torch.dot = 10.0
v1 · v5 via sum(a*b)  = 10.0
Equal? = True

v2 · v4 via torch.dot = 3.0
v2 · v4 via sum(a*b)  = 3.0
Equal? = True

v2 · v3 via torch.dot = 1.0
v2 · v3 via sum(a*b)  = 1.0
Equal? = True

Dot product như weighted sum:
w = tensor([0.500, 0.500, 0.500])
x_vec = tensor([1., 2., 3.])
w · x_vec = tensor(3.)


In [17]:
# Cell 4B-5: Matrix–vector product

print("=== Cụm B.5 – Matrix–vector product ===")

print("A1 =\n", A1)
print("v2 =", v2)
y_mv = A1 @ v2
print("A1 @ v2 =", y_mv)

row0_dot = torch.dot(A1[0], v2)
row1_dot = torch.dot(A1[1], v2)
print("dot(A1[0], v2) =", row0_dot)
print("dot(A1[1], v2) =", row1_dot)

x2 = v2[:2]
print("\nA5 =\n", A5)
print("x2 =", x2)
print("A5 @ x2 =", A5 @ x2)


=== Cụm B.5 – Matrix–vector product ===
A1 =
 tensor([[1., 2., 0.],
        [3., 1., 1.]])
v2 = tensor([1., 2., 3.])
A1 @ v2 = tensor([5., 8.])
dot(A1[0], v2) = tensor(5.)
dot(A1[1], v2) = tensor(8.)

A5 =
 tensor([[ 4., -1.],
        [ 2.,  3.]])
x2 = tensor([1., 2.])
A5 @ x2 = tensor([2., 8.])


In [18]:
# Cell 4B-6: Matrix–matrix multiplication và transpose properties

print("=== Cụm B.6 – Matrix–matrix multiplication, transpose ===")

B1 = torch.tensor([[1., 2.],
                   [3., 4.]])
B2 = torch.tensor([[0., 1.],
                   [-1., 0.]])

print("B1 =\n", B1)
print("B2 =\n", B2)
print("B1 @ B2 =\n", B1 @ B2)
print("B2 @ B1 =\n", B2 @ B1)
print("Equal? (commutativity?) =", torch.allclose(B1 @ B2, B2 @ B1))

print("\nA1, A2 và C = A1 @ A2:")
C = A1 @ A2
print("A1 =\n", A1)
print("A2 =\n", A2)
print("C = A1 @ A2 =\n", C, "shape =", C.shape)

print("\nKiểm tra tính kết hợp (composition):")
x = torch.tensor([1., -1.])
left  = A1 @ (A2 @ x)
right = (A1 @ A2) @ x
print("A2 @ x        =", A2 @ x)
print("A1 @ (A2 @ x) =", left)
print("(A1 @ A2) @ x =", right)
print("Equal? =", torch.allclose(left, right))

print("\nKiểm tra transpose:")
print("(A3.T).T =\n", (A3.T).T)
print("Equal to A3? =", torch.allclose((A3.T).T, A3))

print("\nKiểm tra (A + B).T = A.T + B.T với B = A5 (cùng shape 2x2):")
print("(A3 + A5).T =\n", (A3 + A5).T)
print("A3.T + A5.T =\n", A3.T + A5.T)
print("Equal? =", torch.allclose((A3 + A5).T, A3.T + A5.T))

print("\nMa trận đối xứng A + A.T với A5:")
sym_A5 = A5 + A5.T
print("A5 =\n", A5)
print("A5 + A5.T =\n", sym_A5)
print("sym_A5.T =\n", sym_A5.T)
print("Symmetric? =", torch.allclose(sym_A5, sym_A5.T))


=== Cụm B.6 – Matrix–matrix multiplication, transpose ===
B1 =
 tensor([[1., 2.],
        [3., 4.]])
B2 =
 tensor([[ 0.,  1.],
        [-1.,  0.]])
B1 @ B2 =
 tensor([[-2.,  1.],
        [-4.,  3.]])
B2 @ B1 =
 tensor([[ 3.,  4.],
        [-1., -2.]])
Equal? (commutativity?) = False

A1, A2 và C = A1 @ A2:
A1 =
 tensor([[1., 2., 0.],
        [3., 1., 1.]])
A2 =
 tensor([[ 1.,  0.],
        [ 0.,  1.],
        [ 2., -1.]])
C = A1 @ A2 =
 tensor([[1., 2.],
        [5., 0.]]) shape = torch.Size([2, 2])

Kiểm tra tính kết hợp (composition):
A2 @ x        = tensor([ 1., -1.,  3.])
A1 @ (A2 @ x) = tensor([-1.,  5.])
(A1 @ A2) @ x = tensor([-1.,  5.])
Equal? = True

Kiểm tra transpose:
(A3.T).T =
 tensor([[1., 0.],
        [0., 1.]])
Equal to A3? = True

Kiểm tra (A + B).T = A.T + B.T với B = A5 (cùng shape 2x2):
(A3 + A5).T =
 tensor([[ 5.,  2.],
        [-1.,  4.]])
A3.T + A5.T =
 tensor([[ 5.,  2.],
        [-1.,  4.]])
Equal? = True

Ma trận đối xứng A + A.T với A5:
A5 =
 tensor([[ 4., -1

In [19]:
# Cell 5C-1: So sánh các norm l1, l2, l3 trên nhiều vector

print("=== Cụm C.1 – So sánh các norm l1, l2, l3 ===")

v_outlier = torch.tensor([1., 2., 100.])
vectors_for_norm = [v2, v3, v5, v_outlier]

for x in vectors_for_norm:
    l2 = torch.norm(x, p=2)   # ||x||_2
    l1 = torch.norm(x, p=1)   # ||x||_1
    lp = torch.norm(x, p=3)   # ||x||_3 (ví dụ p=3)
    print("x =", x)
    print("  ||x||_2 =", float(l2))
    print("  ||x||_1 =", float(l1))
    print("  ||x||_3 =", float(lp))
    print()


=== Cụm C.1 – So sánh các norm l1, l2, l3 ===
x = tensor([1., 2., 3.])
  ||x||_2 = 3.7416574954986572
  ||x||_1 = 6.0
  ||x||_3 = 3.301927328109741

x = tensor([-1.,  1.,  0.])
  ||x||_2 = 1.4142135381698608
  ||x||_1 = 2.0
  ||x||_3 = 1.2599210739135742

x = tensor([10.,  0.,  0.])
  ||x||_2 = 10.0
  ||x||_1 = 10.0
  ||x||_3 = 10.000000953674316

x = tensor([  1.,   2., 100.])
  ||x||_2 = 100.02499389648438
  ||x||_1 = 103.0
  ||x||_3 = 100.00031280517578



In [20]:
# Cell 5C-2: Tính chất scale invariance và triangle inequality

print("=== Cụm C.2 – Scale invariance và triangle inequality ===")

test_vectors = [v2, v3]
scalars_for_scale = [alpha2, alpha5]

print("Kiểm tra ||alpha x||_2 = |alpha| ||x||_2:")
for x in test_vectors:
    for a in scalars_for_scale:
        left  = torch.norm(a * x, p=2)
        right = torch.abs(a) * torch.norm(x, p=2)
        print("x =", x, "alpha =", a.item())
        print("  ||alpha x||_2   =", float(left),
              " |alpha| ||x||_2 =", float(right),
              " equal? =", torch.allclose(left, right))
    print()

print("\nKiểm tra bất đẳng thức tam giác ||x + y||_2 <= ||x||_2 + ||y||_2:")
pairs = [(v2, v3), (v2, v4)]
for x, y in pairs:
    lhs = torch.norm(x + y, p=2)
    rhs = torch.norm(x, p=2) + torch.norm(y, p=2)
    print("x =", x, "y =", y)
    print("  ||x + y||_2        =", float(lhs))
    print("  ||x||_2 + ||y||_2 =", float(rhs))
    print("  triangle holds?   =", bool(lhs <= rhs + 1e-6))
    print()


=== Cụm C.2 – Scale invariance và triangle inequality ===
Kiểm tra ||alpha x||_2 = |alpha| ||x||_2:
x = tensor([1., 2., 3.]) alpha = -0.5
  ||alpha x||_2   = 1.8708287477493286  |alpha| ||x||_2 = 1.8708287477493286  equal? = True
x = tensor([1., 2., 3.]) alpha = 2.0
  ||alpha x||_2   = 7.4833149909973145  |alpha| ||x||_2 = 7.4833149909973145  equal? = True

x = tensor([-1.,  1.,  0.]) alpha = -0.5
  ||alpha x||_2   = 0.7071067690849304  |alpha| ||x||_2 = 0.7071067690849304  equal? = True
x = tensor([-1.,  1.,  0.]) alpha = 2.0
  ||alpha x||_2   = 2.8284270763397217  |alpha| ||x||_2 = 2.8284270763397217  equal? = True


Kiểm tra bất đẳng thức tam giác ||x + y||_2 <= ||x||_2 + ||y||_2:
x = tensor([1., 2., 3.]) y = tensor([-1.,  1.,  0.])
  ||x + y||_2        = 4.242640495300293
  ||x||_2 + ||y||_2 = 5.1558709144592285
  triangle holds?   = True

x = tensor([1., 2., 3.]) y = tensor([0.500, 0.500, 0.500])
  ||x + y||_2        = 4.5552167892456055
  ||x||_2 + ||y||_2 = 4.607682704925537
  t

In [21]:
# Cell 5C-3: Norm như khoảng cách – d_p(x, y) = ||x - y||_p

print("=== Cụm C.3 – Norm như khoảng cách ===")

x_ref = v2
x_close   = v2 + torch.tensor([0.01, -0.02, 0.01])
x_far     = v2 + torch.tensor([5., -5., 3.])
x_outlier = v2.clone()
x_outlier[2] = x_outlier[2] + 50.

candidates = [("close",   x_close),
              ("far",     x_far),
              ("outlier", x_outlier)]

print("x_ref =", x_ref)
for name, x in candidates:
    d2 = torch.norm(x_ref - x, p=2)
    d1 = torch.norm(x_ref - x, p=1)
    print(f"Distance from ref to {name}:")
    print("  d2 (Euclid)   =", float(d2))
    print("  d1 (Manhattan)=", float(d1))
    print()


=== Cụm C.3 – Norm như khoảng cách ===
x_ref = tensor([1., 2., 3.])
Distance from ref to close:
  d2 (Euclid)   = 0.024494873359799385
  d1 (Manhattan)= 0.039999961853027344

Distance from ref to far:
  d2 (Euclid)   = 7.681145668029785
  d1 (Manhattan)= 13.0

Distance from ref to outlier:
  d2 (Euclid)   = 50.0
  d1 (Manhattan)= 50.0



In [22]:
# Cell 5C-4: Frobenius norm trên ma trận và liên hệ với vec(X)

print("=== Cụm C.4 – Frobenius norm ===")

matrices_for_norm = [A1, A3, A5]

for X in matrices_for_norm:
    frob   = torch.norm(X)                    # ||X||_F
    vec_l2 = torch.norm(X.reshape(-1), p=2)   # ||vec(X)||_2
    print("X =\n", X)
    print("  ||X||_F      =", float(frob))
    print("  ||vec(X)||_2 =", float(vec_l2))
    print("  equal?       =", torch.allclose(frob, vec_l2))
    print()

print("Kiểm tra tính scale trên ma trận:")
for X in matrices_for_norm:
    for a in [alpha2, alpha5]:
        left  = torch.norm(a * X)
        right = torch.abs(a) * torch.norm(X)
        print("X shape =", X.shape, "alpha =", a.item())
        print("  ||alpha X||_F   =", float(left))
        print("  |alpha| ||X||_F =", float(right))
        print("  equal?          =", torch.allclose(left, right))
    print()


=== Cụm C.4 – Frobenius norm ===
X =
 tensor([[1., 2., 0.],
        [3., 1., 1.]])
  ||X||_F      = 4.0
  ||vec(X)||_2 = 4.0
  equal?       = True

X =
 tensor([[1., 0.],
        [0., 1.]])
  ||X||_F      = 1.4142135381698608
  ||vec(X)||_2 = 1.4142135381698608
  equal?       = True

X =
 tensor([[ 4., -1.],
        [ 2.,  3.]])
  ||X||_F      = 5.4772257804870605
  ||vec(X)||_2 = 5.4772257804870605
  equal?       = True

Kiểm tra tính scale trên ma trận:
X shape = torch.Size([2, 3]) alpha = -0.5
  ||alpha X||_F   = 2.0
  |alpha| ||X||_F = 2.0
  equal?          = True
X shape = torch.Size([2, 3]) alpha = 2.0
  ||alpha X||_F   = 8.0
  |alpha| ||X||_F = 8.0
  equal?          = True

X shape = torch.Size([2, 2]) alpha = -0.5
  ||alpha X||_F   = 0.7071067690849304
  |alpha| ||X||_F = 0.7071067690849304
  equal?          = True
X shape = torch.Size([2, 2]) alpha = 2.0
  ||alpha X||_F   = 2.8284270763397217
  |alpha| ||X||_F = 2.8284270763397217
  equal?          = True

X shape = torch.Size

In [23]:
# Cell 5C-5: Norm như độ lớn của vector lỗi dự đoán

print("=== Cụm C.5 – Norm và lỗi dự đoán ===")

y_true = v2
y_hat1 = v2 + torch.tensor([0.1, -0.1, 0.05])
y_hat2 = v2 + torch.tensor([1.5, -1.0, -2.0])

for name, y_hat in [("y_hat1", y_hat1), ("y_hat2", y_hat2)]:
    e    = y_hat - y_true
    e_l2 = torch.norm(e, p=2)
    e_l1 = torch.norm(e, p=1)
    print(name, "prediction error:")
    print("  e       =", e)
    print("  ||e||_2 =", float(e_l2))
    print("  ||e||_1 =", float(e_l1))
    print()


=== Cụm C.5 – Norm và lỗi dự đoán ===
y_hat1 prediction error:
  e       = tensor([ 0.100, -0.100,  0.050])
  ||e||_2 = 0.15000002086162567
  ||e||_1 = 0.25

y_hat2 prediction error:
  e       = tensor([ 1.500, -1.000, -2.000])
  ||e||_2 = 2.692582368850708
  ||e||_1 = 4.5

