In [10]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

def print_section(title):
    print("\n" + "="*80)
    print(title)
    print("="*80)


In [11]:
print_section("1. Scalars, Vectors, Matrices, Tensors")

# Scalar: tensor bậc 0
scalar = 3.14
print("Scalar:", scalar, "| type:", type(scalar))

# Vector: tensor bậc 1
vec = np.array([1.0, 2.0, 3.0])
print("\nVector v:", vec)
print("Shape:", vec.shape, "| Rank (ndim):", vec.ndim)

# Matrix: tensor bậc 2
mat = np.array([[1.0, 2.0, 3.0],
                [4.0, 5.0, 6.0]])
print("\nMatrix A:\n", mat)
print("Shape:", mat.shape, "| Rank (ndim):", mat.ndim)

# Tensor bậc cao hơn (ví dụ: batch x height x width x channels)
tensor4d = np.random.randn(2, 3, 4, 3)   # (batch, H, W, C)
print("\nTensor 4D X (batch, H, W, C) shape:", tensor4d.shape)
print("Rank (ndim):", tensor4d.ndim)

# Minh hoạ len(X) là kích thước trục 0
print("\nlen(tensor4d):", len(tensor4d), " (kích thước axis 0 / batch size)")



1. Scalars, Vectors, Matrices, Tensors
Scalar: 3.14 | type: <class 'float'>

Vector v: [1. 2. 3.]
Shape: (3,) | Rank (ndim): 1

Matrix A:
 [[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3) | Rank (ndim): 2

Tensor 4D X (batch, H, W, C) shape: (2, 3, 4, 3)
Rank (ndim): 4

len(tensor4d): 2  (kích thước axis 0 / batch size)


In [12]:
print_section("2. Tensor arithmetic & broadcasting")

# Ví dụ 1: cộng vector với từng hàng của ma trận (broadcast theo axis 0)
x = np.array([[1, 2, 3],
              [4, 5, 6]])      # shape (2, 3)
y = np.array([10, 20, 30])     # shape (3,)

print("x (shape {}):\n{}".format(x.shape, x))
print("\ny (shape {}):\n{}".format(y.shape, y))

# y sẽ được broadcast thành shape (2, 3) để cộng với x
z = x + y
print("\n=== x + y (broadcast theo trục 0) ===")
print("z = x + y (shape {}):\n{}".format(z.shape, z))

# Nhân element-wise với scalar
w = x * 2
print("\n=== x * 2 (nhân scalar từng phần tử) ===")
print("w = x * 2 (shape {}):\n{}".format(w.shape, w))


# Ví dụ 2: broadcasting theo trục cột (axis 1)
a = np.arange(6).reshape(2, 3)   # shape (2, 3)
b = np.array([[10],
              [20]])             # shape (2, 1)

print("\n--- Ví dụ broadcasting 2 ---")
print("a (shape {}):\n{}".format(a.shape, a))
print("\nb (shape {}):\n{}".format(b.shape, b))

# b sẽ được broadcast thành shape (2, 3) để cộng với a
c = a + b
print("\n=== a + b (broadcast theo trục cột) ===")
print("c = a + b (shape {}):\n{}".format(c.shape, c))

# Ví dụ 3: broadcasting với tensor 3D và vector 1D
T = np.ones((2, 3, 4))           # shape (2,3,4)
v = np.array([1, 2, 3, 4])       # shape (4,)

print("\n--- Ví dụ broadcasting 3D + 1D ---")
print("T shape:", T.shape)
print("v shape:", v.shape)

# v sẽ broadcast lên (1,1,4) rồi (2,3,4)
T2 = T * v
print("\n=== T * v (broadcast trên trục cuối) ===")
print("T2 shape:", T2.shape)
print("T2[0,0,:] = ", T2[0,0,:])



2. Tensor arithmetic & broadcasting
x (shape (2, 3)):
[[1 2 3]
 [4 5 6]]

y (shape (3,)):
[10 20 30]

=== x + y (broadcast theo trục 0) ===
z = x + y (shape (2, 3)):
[[11 22 33]
 [14 25 36]]

=== x * 2 (nhân scalar từng phần tử) ===
w = x * 2 (shape (2, 3)):
[[ 2  4  6]
 [ 8 10 12]]

--- Ví dụ broadcasting 2 ---
a (shape (2, 3)):
[[0 1 2]
 [3 4 5]]

b (shape (2, 1)):
[[10]
 [20]]

=== a + b (broadcast theo trục cột) ===
c = a + b (shape (2, 3)):
[[10 11 12]
 [23 24 25]]

--- Ví dụ broadcasting 3D + 1D ---
T shape: (2, 3, 4)
v shape: (4,)

=== T * v (broadcast trên trục cuối) ===
T2 shape: (2, 3, 4)
T2[0,0,:] =  [1. 2. 3. 4.]


In [13]:
print_section("3. Reduction & Non-reduction sum")

X = np.arange(2*3*4).reshape(2, 3, 4)
print("Tensor X shape:", X.shape)
print("X:\n", X)

# Tổng toàn bộ phần tử
print("\nnp.sum(X):", np.sum(X))

# Sum theo từng axis
print("\nSum theo axis=0 -> shape (3, 4):")
print(np.sum(X, axis=0))

print("\nSum theo axis=1 -> shape (2, 4):")
print(np.sum(X, axis=1))

print("\nSum theo axis=2 -> shape (2, 3):")
print(np.sum(X, axis=2))

# Non-reduction sum: cộng 2 tensor cùng shape, shape giữ nguyên
A = np.ones((2, 3))
B = 2 * np.ones((2, 3))
C = A + B
print("\nNon-reduction sum: A+B, shape:", C.shape)
print(C)



3. Reduction & Non-reduction sum
Tensor X shape: (2, 3, 4)
X:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

np.sum(X): 276

Sum theo axis=0 -> shape (3, 4):
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

Sum theo axis=1 -> shape (2, 4):
[[12 15 18 21]
 [48 51 54 57]]

Sum theo axis=2 -> shape (2, 3):
[[ 6 22 38]
 [54 70 86]]

Non-reduction sum: A+B, shape: (2, 3)
[[3. 3. 3.]
 [3. 3. 3.]]


In [14]:
print_section("4. Dot product & góc giữa vector")

u = np.array([1.0, 2.0, 3.0])
v = np.array([4.0, 5.0, 6.0])

dot_uv = np.dot(u, v)
print("u:", u)
print("v:", v)
print("Dot product u·v =", dot_uv)

# Tính cos(theta) = (u·v) / (||u|| ||v||)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
cos_theta = dot_uv / (norm_u * norm_v)
print("\n||u||_2 =", norm_u)
print("||v||_2 =", norm_v)
print("cos(theta) =", cos_theta)



4. Dot product & góc giữa vector
u: [1. 2. 3.]
v: [4. 5. 6.]
Dot product u·v = 32.0

||u||_2 = 3.7416573867739413
||v||_2 = 8.774964387392123
cos(theta) = 0.9746318461970762


In [15]:
print_section("5. Matrix–vector product & rotation")

# Ma trận 2x2
A = np.array([[1.0, 2.0],
              [3.0, 4.0]])
x = np.array([0.5, -1.0])

y = A @ x   # tương đương np.dot(A, x)
print("A:\n", A)
print("x:", x)
print("y = A @ x:", y)

# Ma trận quay 2D
theta = np.pi / 4   # 45 độ
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
p = np.array([1.0, 0.0])  # điểm nằm trên trục x
p_rot = R @ p

print("\nMa trận quay R(45°):\n", R)
print("p:", p)
print("p' = R @ p:", p_rot)



5. Matrix–vector product & rotation
A:
 [[1. 2.]
 [3. 4.]]
x: [ 0.5 -1. ]
y = A @ x: [-1.5 -2.5]

Ma trận quay R(45°):
 [[ 0.707 -0.707]
 [ 0.707  0.707]]
p: [1. 0.]
p' = R @ p: [0.707 0.707]


In [16]:
print_section("6. Matrix–matrix product & associativity (demo nhỏ)")

# Dùng kích thước nhỏ để có thể chạy được
m, n, p, q = 4, 5, 3, 2
A = np.random.randn(m, n)
B = np.random.randn(n, p)
C = np.random.randn(p, q)

print("Shapes: A", A.shape, "B", B.shape, "C", C.shape)

# (AB)C
AB = A @ B
ABC_1 = AB @ C

# A(BC)
BC = B @ C
ABC_2 = A @ BC

print("\n(AB)C shape:", ABC_1.shape)
print("A(BC) shape:", ABC_2.shape)
print("2 kết quả có gần như bằng nhau? ->", np.allclose(ABC_1, ABC_2))

# Minh hoạ chi phí (số phép toán lý thuyết) với kích thước tổng quát
def mult_cost(m, n, p):
    return m * n * p

print("\nChi phí lý thuyết m*n*p với kích thước tổng quát:")
print("cost((AB)C) ~ (m*n*p) + (m*p*q)")
print("cost(A(BC)) ~ (n*p*q) + (m*n*q)")



6. Matrix–matrix product & associativity (demo nhỏ)
Shapes: A (4, 5) B (5, 3) C (3, 2)

(AB)C shape: (4, 2)
A(BC) shape: (4, 2)
2 kết quả có gần như bằng nhau? -> True

Chi phí lý thuyết m*n*p với kích thước tổng quát:
cost((AB)C) ~ (m*n*p) + (m*p*q)
cost(A(BC)) ~ (n*p*q) + (m*n*q)


In [17]:
print_section("7. Norms: l1, l2, linf, Frobenius")

x = np.array([1.0, -2.0, 3.0])
A = np.array([[1.0, -2.0],
              [3.0,  4.0]])

# Vector norms
l1 = np.linalg.norm(x, ord=1)
l2 = np.linalg.norm(x, ord=2)
linf = np.linalg.norm(x, ord=np.inf)

print("Vector x:", x)
print("||x||_1 =", l1)
print("||x||_2 =", l2)
print("||x||_∞ =", linf)

# Frobenius norm cho ma trận
fro = np.linalg.norm(A, ord="fro")
print("\nMatrix A:\n", A)
print("||A||_F (Frobenius) =", fro)



7. Norms: l1, l2, linf, Frobenius
Vector x: [ 1. -2.  3.]
||x||_1 = 6.0
||x||_2 = 3.7416573867739413
||x||_∞ = 3.0

Matrix A:
 [[ 1. -2.]
 [ 3.  4.]]
||A||_F (Frobenius) = 5.477225575051661


In [18]:
print_section("8. Stack 3 matrices thành tensor và slice lại B")

A = np.ones((3, 4))          # 3x4
B = 2 * np.ones((3, 4))
C = 3 * np.ones((3, 4))

# Stack theo trục thứ ba (axis=2) -> shape (3, 4, 3)
T = np.stack([A, B, C], axis=2)
print("Shape của A,B,C:", A.shape)
print("Tensor T shape:", T.shape)

# Kiểm tra indexing: T[:,:,0] = A, T[:,:,1] = B, T[:,:,2] = C
print("\nT[:,:,0] (nên là A):\n", T[:, :, 0])
print("\nT[:,:,1] (nên là B):\n", T[:, :, 1])
print("\nT[:,:,2] (nên là C):\n", T[:, :, 2])

print("\nSlice ra B từ T: B_recovered = T[:,:,1]")
B_recovered = T[:, :, 1]
print("B_recovered shape:", B_recovered.shape)
print("B_recovered:\n", B_recovered)
print("B_recovered có bằng B gốc không? ->", np.allclose(B_recovered, B))



8. Stack 3 matrices thành tensor và slice lại B
Shape của A,B,C: (3, 4)
Tensor T shape: (3, 4, 3)

T[:,:,0] (nên là A):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

T[:,:,1] (nên là B):
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]

T[:,:,2] (nên là C):
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]

Slice ra B từ T: B_recovered = T[:,:,1]
B_recovered shape: (3, 4)
B_recovered:
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
B_recovered có bằng B gốc không? -> True
